# Generated by Django 5.2 on 2025-05-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
