# Generated by Django 5.2 on 2025-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_resume_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
