# Generated by Django 5.2 on 2025-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidate_updated_at_alter_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='domain_classification',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_years_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
